project:
  type: website
  output-dir: docs

website:
  title: "mrgsolve blog"
  search:
    location: navbar
    type: overlay
  navbar:
    background: "#097f5f"
    right:
      - text: Home
        href: https://mrgsolve.org
      - about.qmd
      - icon: github
        href: https://github.com/metrumresearchgroup/mrgsolve
      - icon: twitter
        href: https://twitter.com/mrgsolve
format:
  html:
    theme: default
    css: styles.css



