---
title: Reproducible results with set.seed
author: Kyle Baron
date: 4/23/2022
description: > 
  This post demonstrates that random simulation outputs can be made reproducible
  by using `set.seed()`.
---


```{r, message = FALSE}
#| message: false
#| warning: false
library(mrgsolve)
library(dplyr)
```


# Demo model
```{r}
code <- '
$PKMODEL cmt="CENT"
$PARAM CL = 1, V = 20

$OMEGA 1 1

$TABLE
capture ETA1 = ETA(1);
capture ETA2 = ETA(2);
'
```


```{r,message=FALSE}
mod <- mcode("test", code)
```

# Single dose

```{r}
set.seed(9911)
single <- mod %>% ev(amt=100) %>% mrgsim(nid=100, end=24)

```

# Multi dose 
```{r}
set.seed(9911)
multi <- mod %>% ev(amt=100, ii=24, addl=9) %>% mrgsim(nid=100, end=240)
```



# Compare
```{r,comment='.'}
single
multi
```

```{r,comment='.'}
filter(single, CENT==0)
filter(multi, CENT==0)
```





## Identical in the first day ...
```{r,comment='.'}
identical(filter(single, time < 24),filter(multi,time < 24))
```

## ... but not after that
```{r,comment='.'}
filter(single, time > 24)
filter(multi, time > 24)
```






